import Link from "next/link";
import FooterPage from "./components/FooterPage";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="justify-between bg-white p-4 flex-row flex">
        <div className="text-black text-lg font-bold">
          <Link className="mr-4" href="/">
            Home
          </Link>
          <Link className="mr-4" href="/list">
            List
          </Link>
          <Link className="mr-4" href="/intro">
            소개
          </Link>
        </div>
        <div className="text-black text-lg font-bold">
          <Link className="mr-4" href="/cart">
            MENU
          </Link>
        </div>
      </div>
      {children}
      <FooterPage />
    </html>
  );
}
