import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="justify-between bg-white p-4 flex-row flex">
        <div className="text-black text-lg font-bold">
          <Link className="mr-4" href="/">
            Home
          </Link>
          <Link className="mr-4" href="/list">
            List
          </Link>
          <Link className="mr-4" href="/intro">
            소개
          </Link>
        </div>
        <div className="text-black text-lg font-bold">
          <Link className="mr-4" href="/cart">
            MENU
          </Link>
        </div>
      </div>
      {children}
      <footer>
        <div className="p-20 bg-white">
          <h4 className="font-bold text-xl">Production by J</h4>
          <div className="flex flex-row">
            <p className="text-lg font-bold">TEL.</p>
            <p className="text-lg mr-4">1234-5678</p>
            <p className="text-lg font-bold">E-MAIL.</p>
            <p className="text-lg mr-4">production@gmail.co.kr</p>
          </div>
          <div className="mt-5">
            <p>서울특별시 가나다라 123-1</p>
            <p>통신판매업종신고 : 제1111-서울-123 상호:product 대표:홍길동</p>
            <p>고객센터:1234-5678 이메일:production@gmail</p>
          </div>
        </div>
      </footer>
    </html>
  );
}
